### ISSUE TITLE
Init USB-CAN

### ISSUE THREAD

**Issue by vespadj** [vekexasia/comfoairq-mqtt#1]
Ciao @vekexasia , in questo issue: https://github.com/marco-hoyer/zcan/issues/1#issuecomment-762716806
hai scritto:

> Apparently i had commented out from my code the S2\r and 0\r code. So the usbtin never initialized itself....

vedo in index.ts e dist/index.js che queste righe sono ancora commentate.
In VS Code mi da errore in index.ts:96  "r();" , pare che manchi un void... 
Quindi tsc non compila.

Da Home Assistant / Sviluppo lancio con mqtt.publish i comandi, e nel console log di `pm2 start pm2.config.js` vedo 
che la porta è aperta e i messaggi lanciati con mqtt.publish si tramutano in steam dati per la porta seriale. Ma il led sulla ComfoAir lampeggia veloce e nel suo display non cambia nulla.

**Comment by vekexasia** [comment]
Ciao @vespadj effettivamente mi ero dimenticato di updatare. Per l'errore di tsc. Meglio se mi dai un errore piu completo.

che versione hai della comfoair?

**Comment by vespadj** [comment]
con tsc --version 4.1.5
mi segna un errore TS2794 che ho risolto con `await new Promise<void>`

ComfoAir Q350 I R ST
fw: R1.6.0

**Comment by vespadj** [comment]
dist/index.js:60

Serial Port open!
w undefined
ww undefined
