### ISSUE TITLE
support for RS485 CAN hat

### ISSUE THREAD

**Issue by svde** [vekexasia/comfoairq-mqtt#3]
I see that currently only USBtin is supported. Would it be possible to also support the RS485 CAN hat for the raspberry pi, made by waveshare: https://www.waveshare.com/rs485-can-hat.htm

I have this device on a pi zero w. It's visible as a can0 network interface:

$ ifconfig can0
can0: flags=193<UP,RUNNING,NOARP>  mtu 16
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 10  (UNSPEC)
        RX packets 2382522  bytes 3877541 (3.6 MiB)
        RX errors 1  dropped 221  overruns 0  frame 1
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

and I'm able to see the can traffic:

$ candump can0
  can0  004C4041   [2]  24 00
  can0  001E4041   [2]  8F 05
  can0  00354041   [2]  06 04
  can0  10000002   [0]
  can0  00804042   [2]  0C 00
  can0  10000001   [0]
  can0  001DC041   [2]  C5 00
  can0  001E8041   [2]  4A 05
  can0  004C8041   [2]  25 00
  can0  001E4041   [2]  8E 05

**Comment by vekexasia** [comment]
Hey, i dont have the time now to support the can hat. I wrote the ESP32 integration you can read about here.

**Comment by svde** [comment]
Understood.

I've ordered parts to build the ESP32.

FYI: I have a Q350 + option box. Perhaps I can contribute by reverse engineering some of the commands specific to the option box, especially the 0-10V inputs.

**Comment by vekexasia** [comment]
@svde What is the option box? :) never heard of it.

**Comment by vekexasia** [comment]
PS: apparently i didn't attach the gh repo of esp32 -> https://github.com/vekexasia/comfoair-esp32

**Comment by svde** [comment]
> @svde What is the option box? :) never heard of it.

See: https://www.manualslib.de/manual/614411/Zehnder-Optionbox.html#manual
